#!/usr/bin/env bash
# tools/integrity.sh — OLMO repo invariant checker
#
# Read-only: verifies declarative claims compile against filesystem.
# Does NOT fix violations — only reports. Human decides remediation.
#
# Invariants:
#   INV-2: Every hook registered in .claude/settings.local.json exists
#          and passes bash syntax check.
#   INV-5: No untracked pollution dirs (.claude/.claude/, .claude/tmp/)
#          present on filesystem.
#
# Grow incrementally: add INV-1 md-destino, INV-3 pointer-resolution
# in future commits. INV-4 count-integrity added in S271 (audit §7 ALTO).
#
# Usage: tools/integrity.sh
#   env SESSION=S221  — override session label in report header
# Exit: 0 if all invariants pass, 1 if any violation.
# Writes: .claude/integrity-report.md (overwrites each run).

set -euo pipefail

PROJECT_ROOT="${CLAUDE_PROJECT_DIR:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
cd "$PROJECT_ROOT"

REPORT="${PROJECT_ROOT}/.claude/integrity-report.md"
SESSION="${SESSION:-$(date +S%Y%m%d)}"
TS="$(date '+%Y-%m-%d %H:%M')"

VIOLATIONS=0
INV_COUNT=0

{
  echo "# Integrity Report — ${SESSION} ${TS}"
  echo ""
  echo "> Generated by tools/integrity.sh. Read-only; does not fix."
  echo ""
} > "$REPORT"

check_inv_2() {
  INV_COUNT=$((INV_COUNT + 1))
  printf '## INV-2 Hook registration\n\n' >> "$REPORT"

  local total=0
  local missing=0
  local nonexec=0
  local path full event cmd

  while IFS=$'\t' read -r event cmd; do
    [[ -z "$cmd" || "$cmd" == "null" ]] && continue
    total=$((total + 1))

    if [[ "$cmd" =~ ^bash[[:space:]]\$CLAUDE_PROJECT_DIR/ ]]; then
      path="${cmd#bash \$CLAUDE_PROJECT_DIR/}"
      path="${path%% *}"
    else
      printf -- '- [SKIP] %s: unparseable `%s`\n' "$event" "$cmd" >> "$REPORT"
      continue
    fi

    full="${PROJECT_ROOT}/${path}"
    if [[ ! -f "$full" ]]; then
      printf -- '- [FAIL] %s: %s — missing\n' "$event" "$path" >> "$REPORT"
      missing=$((missing + 1))
      VIOLATIONS=$((VIOLATIONS + 1))
    elif ! bash -n "$full" 2>/dev/null; then
      printf -- '- [FAIL] %s: %s — syntax error\n' "$event" "$path" >> "$REPORT"
      nonexec=$((nonexec + 1))
      VIOLATIONS=$((VIOLATIONS + 1))
    else
      printf -- '- [PASS] %s: %s\n' "$event" "$path" >> "$REPORT"
    fi
  done < <(jq -rs '(.[0] // {}) * (.[1] // {}) | .hooks // {} | to_entries[] | .key as $e | .value[] | (.hooks // [])[] | "\($e)\t\(.command // "null")"' .claude/settings.json .claude/settings.local.json 2>/dev/null | tr -d '\r')

  {
    echo ""
    echo "Total: ${total} registered, $((total - missing - nonexec)) valid, ${missing} missing, ${nonexec} syntax errors"
    echo ""
  } >> "$REPORT"
}

check_inv_4() {
  INV_COUNT=$((INV_COUNT + 1))
  printf '## INV-4 Count integrity (FS vs declarative docs)\n\n' >> "$REPORT"

  local fs_agents fs_skills
  fs_agents=$(find .claude/agents -maxdepth 1 -name '*.md' 2>/dev/null | wc -l | tr -d ' ')
  fs_skills=$(find .claude/skills -mindepth 2 -maxdepth 2 -name 'SKILL.md' 2>/dev/null | wc -l | tr -d ' ')

  local docs=("CLAUDE.md" "README.md" "docs/ARCHITECTURE.md")
  local doc agents_in skills_in violations=0

  for doc in "${docs[@]}"; do
    if [[ ! -f "$doc" ]]; then
      printf -- '- [SKIP] %s: missing\n' "$doc" >> "$REPORT"
      continue
    fi

    agents_in=$(grep -oE -- '- [0-9]+ subagents' "$doc" 2>/dev/null | head -1 | grep -oE '[0-9]+' || true)
    skills_in=$(grep -oE -- '- [0-9]+ skills' "$doc" 2>/dev/null | head -1 | grep -oE '[0-9]+' || true)

    if [[ -z "$agents_in" && -z "$skills_in" ]]; then
      printf -- '- [SKIP] %s: no declarative counts found\n' "$doc" >> "$REPORT"
      continue
    fi

    if [[ -n "$agents_in" ]]; then
      if [[ "$agents_in" != "$fs_agents" ]]; then
        printf -- '- [FAIL] %s: claims %s subagents, FS=%s\n' "$doc" "$agents_in" "$fs_agents" >> "$REPORT"
        violations=$((violations + 1))
        VIOLATIONS=$((VIOLATIONS + 1))
      else
        printf -- '- [PASS] %s: %s subagents matches FS\n' "$doc" "$agents_in" >> "$REPORT"
      fi
    fi

    if [[ -n "$skills_in" ]]; then
      if [[ "$skills_in" != "$fs_skills" ]]; then
        printf -- '- [FAIL] %s: claims %s skills, FS=%s\n' "$doc" "$skills_in" "$fs_skills" >> "$REPORT"
        violations=$((violations + 1))
        VIOLATIONS=$((VIOLATIONS + 1))
      else
        printf -- '- [PASS] %s: %s skills matches FS\n' "$doc" "$skills_in" >> "$REPORT"
      fi
    fi
  done

  {
    echo ""
    echo "FS truth: ${fs_agents} agents, ${fs_skills} skills"
    echo "Total: ${violations} violations"
    echo ""
  } >> "$REPORT"
}

check_inv_5() {
  INV_COUNT=$((INV_COUNT + 1))
  printf '## INV-5 Untracked pollution\n\n' >> "$REPORT"

  local count dir
  local orphan_dirs=(".claude/.claude" ".claude/tmp")
  local violations=0

  for dir in "${orphan_dirs[@]}"; do
    if [[ -d "$dir" ]]; then
      count=$(find "$dir" -type f 2>/dev/null | wc -l | tr -d ' ')
      printf -- '- [FAIL] %s/ present (%s files)\n' "$dir" "$count" >> "$REPORT"
      violations=$((violations + 1))
      VIOLATIONS=$((VIOLATIONS + 1))
    else
      printf -- '- [PASS] %s/ absent\n' "$dir" >> "$REPORT"
    fi
  done

  {
    echo ""
    echo "Total: ${violations} violations"
    echo ""
  } >> "$REPORT"
}

check_inv_2
check_inv_4
check_inv_5

{
  echo "---"
  echo ""
  echo "## Summary"
  echo ""
  echo "${INV_COUNT} invariants checked, ${VIOLATIONS} violations."
  if [[ $VIOLATIONS -eq 0 ]]; then
    echo ""
    echo "All checks passed."
  fi
} >> "$REPORT"

printf 'integrity.sh: %d invariants, %d violations\nReport: %s\n' "$INV_COUNT" "$VIOLATIONS" "$REPORT"

[[ $VIOLATIONS -eq 0 ]] && exit 0 || exit 1
